baseURL = 'https://gitsakar.github.io'
languageCode = 'en-us'
title = 'Sakar Pudasaini'

theme = "m10c"

[params]
  author = "Sakar Pudasaini"
  description = "Blog on Networks"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/gitsakar"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/PudasainiSakar"